name: Lint Code Base

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-lint:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🧹 Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: "main"
